# Generated by Django 4.0.5 on 2022-06-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplicate_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile1', models.CharField(max_length=100)),
                ('profile2', models.CharField(max_length=100)),
                ('total_match_score', models.IntegerField()),
                ('matching_attributes', models.TextField(blank=True)),
                ('non_matching_attributes', models.TextField(blank=True)),
                ('ignored_attributes', models.TextField(blank=True)),
            ],
        ),
    ]
