# Generated by Django 4.0.5 on 2022-06-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_duplicate_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
